spring:
  application:
    name: DevNet
  profiles:
    active: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    baseline-description: "init"
    baseline-version: 0
    locations: classpath:db/migration

# actuator settings
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.security: DEBUG
