spring:
  application:
    name: DevNet
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    baseline-description: "init"
    baseline-version: 0
# actuator settings
management:
  endpoints:
    web:
      exposure:
        include: "*"
